lib/todex_web/router.ex
defmodule TodexWeb.Router do
  use TodexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TodexWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/registrations", UserController, only: [:create, :new]

    resources "/projects", ProjectController

    resources "/tasks", TaskController do
      put "/done", TaskController, :done
      put "/undone", TaskController, :undone
    end

    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-out", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodexWeb do
  #   pipe_through :api
  # end
end

lib/todex/todos/task.ex
defmodule Todex.Todos.Task do
  use Ecto.Schema
  import Ecto.Changeset

  alias Todex.Accounts.User
  alias Todex.Todos.Category
  alias Todex.Todos.Project

  schema "tasks" do
    field :conclusion_date, :naive_datetime
    field :description, :string
    field :is_concluded, :boolean, default: false
    field :title, :string

    belongs_to :user, User
    belongs_to :category, Category

    many_to_many :projects,
                 Project,
                 join_through: "task_projects",
                 on_replace: :delete

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:title, :description, :conclusion_date, :is_concluded, :category_id, :user_id])
    |> maybe_put_projects(attrs)
    |> validate_required([:title])
  end

  defp maybe_put_projects(changeset, %{projects: projects}), do: put_projects(changeset, projects)

  defp maybe_put_projects(changeset, %{"projects": projects}), do: put_projects(changeset, projects)

  defp maybe_put_projects(changeset, _), do: changeset

  defp put_projects(changeset, projects), do: Ecto.Changeset.put_assoc(changeset, :projects, projects)

end

lib/todex_web/controllers/task_controller.ex
defmodule TodexWeb.TaskController do
  use TodexWeb, :controller

  alias Todex.Todos
  alias Todex.Todos.Task
  alias TodexWeb.Helpers.Auth

  plug :check_auth

  def index(conn, params) do
    current_user = Auth.current_user(conn)
    tasks = Todos.list_tasks(current_user.id, params)
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset =
      %Task{}
      |> Todos.preload_projects()
      |> Todos.change_task()

    categories = Todos.list_categories()

    current_user = Auth.current_user(conn)
    projects = Todos.list_projects(current_user.id)

    render(conn, "new.html", changeset: changeset, categories: categories, projects: projects)
  end

  def create(conn, %{"task" => task_params}) do
    current_user = Auth.current_user(conn)
    task_params = Map.put(task_params, "user_id", current_user.id)

    selected_projects =
      task_params
      |> Map.get("project_ids", [])
      |> Todos.list_projects_id_in()

    task_params = Map.put(task_params, "projects", selected_projects)

    case Todos.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        categories = Todos.list_categories()
        projects = Todos.list_projects(current_user.id)
        data = Todos.preload_projects(changeset.data)

        render(conn, "new.html",
          changeset: %{changeset | data: data},
          categories: categories,
          projects: projects
        )
    end
  end

  def show(conn, %{"id" => id}) do
    task = Todos.get_task!(id)
    render(conn, "show.html", task: task)
  end

  def edit(conn, %{"id" => id}) do
    task = Todos.get_task!(id)
    changeset = Todos.change_task(task)
    categories = Todos.list_categories()
    projects = current_user_projects(conn)

    render(conn, "edit.html",
      task: task,
      changeset: changeset,
      categories: categories,
      projects: projects
    )
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Todos.get_task!(id)

    selected_projects =
      task_params
      |> Map.get("project_ids", [])
      |> Todos.list_projects_id_in()

    task_params = Map.put(task_params, "projects", selected_projects)

    case Todos.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        categories = Todos.list_categories()
        projects = current_user_projects(conn)

        render(conn, "edit.html",
          task: task,
          changeset: changeset,
          categories: categories,
          projects: projects
        )
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Todos.get_task!(id)
    {:ok, _task} = Todos.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end

  def done(conn, %{"task_id" => id}) do
    case Todos.mark_task_done(id) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task marked as done")
        |> redirect(to: Routes.task_path(conn, :index))

      {:error, _} ->
        conn
        |> put_flash(:error, "Failed to mark task as done")
        |> redirect(to: Routes.task_path(conn, :index))
    end
  end

  def undone(conn, %{"task_id" => id}) do
    case Todos.mark_task_undone(id) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task marked as undone")
        |> redirect(to: Routes.task_path(conn, :index))

      {:error, _} ->
        conn
        |> put_flash(:error, "Failed to mark task as undone")
        |> redirect(to: Routes.task_path(conn, :index))
    end
  end

  defp current_user_projects(conn) do
    current_user = Auth.current_user(conn)
    Todos.list_projects(current_user.id)
  end

  defp check_auth(conn, _args) do
    unless Auth.signed_in?(conn) do
      conn
      |> put_flash(:error, "You need to be signed")
      |> redirect(to: Routes.page_path(conn, :index))
      |> halt()
    else
      conn
    end
  end
end

lib/todex_web/views/task_view.ex
defmodule TodexWeb.TaskView do
  use TodexWeb, :view
end

lib/todex_web/templates/task/edit.html.eex
<h1>Edit Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/todex_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= textarea f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :category_id, for: "categoryField" %>
  <%= select f, :category_id, Enum.map(@categories, &{&1.name, &1.id}), id: "categoryField" %>
  <%= error_tag f, :category_id %>
  
  <%= label f, :projects, for: "projectsField" %>
  <%= multiple_select f, 
      :project_ids, 
      Enum.map(@projects, &{&1.name, &1.id}), 
      selected: Enum.map(@changeset.data.projects, &(&1.id)),
      id: "projectsField" %>
  <%= error_tag f, :project_ids %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/todex_web/templates/task/index.html.eex
<h1>Listing Tasks</h1>
<%= form_for @conn, Routes.task_path(@conn, :index), [method: :get], fn f -> %>
  <div class="row">
    <%= search_input f, :query %>
    <%= submit "Search" %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td>
      <%= if task.is_concluded do %>
        <span><%= link "Mark as undone", to: Routes.task_task_path(@conn, :undone, task), method: :put %></span>
      <% else %>
        <span><%= link "Mark as done", to: Routes.task_task_path(@conn, :done, task), method: :put %></span>
      <% end %>
      </td>

      <td>
        <span><%= link "Show", to: Routes.task_path(@conn, :show, task) %></span>
        <span><%= link "Edit", to: Routes.task_path(@conn, :edit, task) %></span>
        <span><%= link "Delete", to: Routes.task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<span><%= link "New Task", to: Routes.task_path(@conn, :new) %></span>

lib/todex_web/templates/task/new.html.eex
<h1>New Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/todex_web/templates/task/show.html.eex
<h1>Show Task</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @task.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @task.description %>
  </li>

  <li>
    <strong>Category:</strong>
    <%= if @task.category do %>
      <%= @task.category.name %>
    <% else %>
      Not selected
    <% end %>
  </li>

  <%= if @task.is_concluded do %>
  <li>
    <strong>Conclusion date:</strong>
    <%= @task.conclusion_date %>
  </li>

  <li>
    <strong>Is concluded:</strong>
    <%= @task.is_concluded %>
  </li>
  <% end %>

</ul>

<span><%= link "Edit", to: Routes.task_path(@conn, :edit, @task) %></span>
<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>